package com.pyamsoft.tetherfi.status

internal enum class StatusScreenContentTypes {
  BUTTON,
  STATUS,
  LOADING,
  SPACER,
  BOTTOM_SPACER,
  NETWORK_ERROR,
  EDIT_SSID,
  EDIT_PASSWD,
  EDIT_PORT,
  VIEW_HOWTO,
  VIEW_SSID,
  VIEW_PASSWD,
  VIEW_PROXY,
  TILES,
  BANDS,
  BATTERY_LABEL,
  BATTERY_OPTIMIZATION,
  WAKELOCKS,
  TWEAK_LABEL,
  TWEAKS,
}
